-- +migrate Up
CREATE TABLE `users` (
	`ID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name`   VARCHAR(255) NOT NULL,
	`Github` VARCHAR(255) NOT NULL,
	`Image`  VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
) ENGINE=InnoDB;

CREATE TABLE `seats` (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`ID`)
) ENGINE=InnoDB;

CREATE TABLE `seats_users` (
	`SeatID` INT UNSIGNED NOT NULL,
	`UserID` TINYINT UNSIGNED NOT NULL,
	PRIMARY KEY(`SeatID`, `UserID`)
) ENGINE=InnoDB;

-- +migrate Down
DROP TABLE `users`;
DROP TABLE `seats`;
DROP TABLE `seats_users`;
